{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cdn-manager.serviceAccountName" . }}
  labels:
    {{- include "cdn-manager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cdn-manager.serviceAccountName" . }}
  labels:
    {{- include "cdn-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cdn-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "cdn-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}

