# permissions for end users to edit clusterdistributionclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterdistributionclass-editor-role
rules:
- apiGroups:
  - cdn.redcoat.dev
  resources:
  - clusterdistributionclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cdn.redcoat.dev
  resources:
  - clusterdistributionclasses/status
  verbs:
  - get
