# permissions for end users to view clusterdistributionclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterdistributionclass-viewer-role
rules:
- apiGroups:
  - cdn.redcoat.dev
  resources:
  - clusterdistributionclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cdn.redcoat.dev
  resources:
  - clusterdistributionclasses/status
  verbs:
  - get
