# permissions for end users to view distributionclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: distributionclass-viewer-role
rules:
- apiGroups:
  - cdn.redcoat.dev
  resources:
  - distributionclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cdn.redcoat.dev
  resources:
  - distributionclasses/status
  verbs:
  - get
