# permissions for end users to edit distributions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: distribution-editor-role
rules:
- apiGroups:
  - cdn.redcoat.dev
  resources:
  - distributions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cdn.redcoat.dev
  resources:
  - distributions/status
  verbs:
  - get
