# permissions for end users to edit distributionclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: distributionclass-editor-role
rules:
- apiGroups:
  - cdn.redcoat.dev
  resources:
  - distributionclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cdn.redcoat.dev
  resources:
  - distributionclasses/status
  verbs:
  - get
