# permissions for end users to view distributions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: distribution-viewer-role
rules:
- apiGroups:
  - cdn.redcoat.dev
  resources:
  - distributions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cdn.redcoat.dev
  resources:
  - distributions/status
  verbs:
  - get
