// +build !ignore_autogenerated

/*
Copyright 2021 Red Coat Development Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package cloudfront

import (
	"github.com/jetstack/cert-manager/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudFrontSpec) DeepCopyInto(out *CloudFrontSpec) {
	*out = *in
	if in.SecretAccessKey != nil {
		in, out := &in.SecretAccessKey, &out.SecretAccessKey
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.SupportedMethods != nil {
		in, out := &in.SupportedMethods, &out.SupportedMethods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudFrontSpec.
func (in *CloudFrontSpec) DeepCopy() *CloudFrontSpec {
	if in == nil {
		return nil
	}
	out := new(CloudFrontSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudFrontStatus) DeepCopyInto(out *CloudFrontStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudFrontStatus.
func (in *CloudFrontStatus) DeepCopy() *CloudFrontStatus {
	if in == nil {
		return nil
	}
	out := new(CloudFrontStatus)
	in.DeepCopyInto(out)
	return out
}
